https://github.com/ipython/ipyparallel/pull/818

commit 47aba76d77b1ae83463badcd1a9002c74cc454cc
Author: Miro Hronƒçok <miro@hroncok.cz>
Date:   Mon Jul 3 20:52:18 2023 +0200

    Fix unittest.mock usage on Python 3.12

diff --git a/ipyparallel/tests/test_util.py b/ipyparallel/tests/test_util.py
index f4e0c953..eb1e11dc 100644
--- a/ipyparallel/tests/test_util.py
+++ b/ipyparallel/tests/test_util.py
@@ -14,7 +14,7 @@ def test_disambiguate_ip(warn_mock):
     assert util.disambiguate_ip_address('0.0.0.0', socket.gethostname()) == localhost()
     wontresolve = 'this.wontresolve.dns'
     assert util.disambiguate_ip_address('0.0.0.0', wontresolve) == wontresolve
-    assert warn_mock.called_once_with(
+    warn_mock.assert_called_once_with(
         'IPython could not determine IPs for {}: '
         '[Errno -2] Name or service not known'.format(wontresolve),
         RuntimeWarning,
