From 305678ec85568e9fdbc888078c11a1f7d4bc0100 Mon Sep 17 00:00:00 2001
From: Merlijn Wajer <merlijn@wizzup.org>
Date: Sat, 14 Dec 2019 18:16:30 +0800
Subject: [PATCH] program/cdparanoia: fix failed() task of AnalyzeTask

---
 whipper/program/cdparanoia.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/whipper/program/cdparanoia.py b/whipper/program/cdparanoia.py
index 636e6f5..f071674 100644
--- a/whipper/program/cdparanoia.py
+++ b/whipper/program/cdparanoia.py
@@ -603,7 +603,7 @@ class AnalyzeTask(ctask.PopenTask):
     def failed(self):
         # cdparanoia exits with return code 1 if it can't determine
         # whether it can defeat the audio cache
-        output = "".join(self._output)
+        output = "".join(o.decode() for o in self._output)
         m = _WARNING_RE.search(output)
         if m or _ABORTING_RE.search(output):
             self.defeatsCache = False
-- 
2.17.1
